//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsgNet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OSG_UseThread {
            get {
                return ((bool)(this["OSG_UseThread"]));
            }
            set {
                this["OSG_UseThread"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lowest")]
        public global::System.Threading.ThreadPriority OSG_ThreadPriority {
            get {
                return ((global::System.Threading.ThreadPriority)(this["OSG_ThreadPriority"]));
            }
            set {
                this["OSG_ThreadPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OSG_UseTimer {
            get {
                return ((bool)(this["OSG_UseTimer"]));
            }
            set {
                this["OSG_UseTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int OSG_TimerInterval {
            get {
                return ((int)(this["OSG_TimerInterval"]));
            }
            set {
                this["OSG_TimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OSG_UseGraphicsThread {
            get {
                return ((bool)(this["OSG_UseGraphicsThread"]));
            }
            set {
                this["OSG_UseGraphicsThread"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int OSG_NumSamples {
            get {
                return ((int)(this["OSG_NumSamples"]));
            }
            set {
                this["OSG_NumSamples"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public uint OSG_Stencil {
            get {
                return ((uint)(this["OSG_Stencil"]));
            }
            set {
                this["OSG_Stencil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public uint OSG_Depth {
            get {
                return ((uint)(this["OSG_Depth"]));
            }
            set {
                this["OSG_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public uint OSG_Red {
            get {
                return ((uint)(this["OSG_Red"]));
            }
            set {
                this["OSG_Red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public uint OSG_Green {
            get {
                return ((uint)(this["OSG_Green"]));
            }
            set {
                this["OSG_Green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public uint OSG_Blue {
            get {
                return ((uint)(this["OSG_Blue"]));
            }
            set {
                this["OSG_Blue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public uint OSG_Alpha {
            get {
                return ((uint)(this["OSG_Alpha"]));
            }
            set {
                this["OSG_Alpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWAP_DEFAULT")]
        public global::osg.DisplaySettings.SwapMethod OSG_SwapMethod {
            get {
                return ((global::osg.DisplaySettings.SwapMethod)(this["OSG_SwapMethod"]));
            }
            set {
                this["OSG_SwapMethod"] = value;
            }
        }
    }
}
